# Generated by Django 3.2 on 2021-05-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_vypujcka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vypujcka',
            name='datum_a_cas_konec_vypujcky',
            field=models.DateField(),
        ),
    ]
